### ISSUE TITLE
requesting two entity options 'basePackageName' and 'idType' for JDL

### ISSUE THREAD

**Issue by NKU915** [jhipster/jhipster-uml#122]
Current generated domain files are missing base package name and ID data type,
It looks like:
```
package .domain;

    public  getId() {
        return id;
    }
    public void setId( id) {
        this.id = id;
    }
```

can add two options basePackageName and idType for JDL? 
for example:
```

entity Author {
  name String required,
  birthDate LocalDate
}
basePackageName com.mycompany.myapp
idTypte Author Long

```
The generated domain would look like:
```
pacakge com.mycompany.myapp.domain;

public class Author  implements Serializable{
     private Long id;

    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
```

Many thanks.

**Comment by MathieuAA** [comment]
Hi, can you please post your input file (the JDL or the XMI file)?
I didn't have this bug.

**Comment by NKU915** [comment]
the  test.jh is extracted from:
     https://jhipster.github.io/jhipster-uml/#jdl
and command is: 
     jhipster-uml yourfile.jh -db sql

```
entity Book {
  title String required,
  description String required minlength(5) maxlength(50),
  publicationDate LocalDate,
  price BigDecimal
}
entity Author {
  name String required,
  birthDate LocalDate
}
relationship OneToMany {
  Author{book} to Book{writer(name)}
}
```

**Comment by MathieuAA** [comment]
I won't add these options in the JDL because you tried to generate entities outside the scope of a JHipster app. Using JHipster UML this way is the same as not doing `yo jhipster:entity SOMETHING` in a JHipster app.
JHipster itself won't generate all the files when one does `yo jhipster:entity SOMETHING` like you did. However, I agree it would be nice to have all the missing pieces when doing this command the way you did.

**Comment by NKU915** [comment]
got it,thanks
