### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by lfdubiela** [jhipster/jhipster-uml#147]
I've got this error but I still didn't get it, I looked at my diagram and i can't find where is it, I looked at your code trying to change in order to show where is circular dependency;;

**Comment by lfdubiela** [comment]
[orange.zip](https://github.com/jhipster/jhipster-uml/files/137230/orange.zip)

**Comment by MathieuAA** [comment]
I can't look at it right now. I'll see what the problem is tonight. In the meantime, I've created #148.

**Comment by MathieuAA** [comment]
You have A LOT of entities. It will take me some time to analyze all that information.

**Comment by MathieuAA** [comment]
I'm going to list some of the problems I see here in order to help you:
  - For `Material` and `Unidade`, you misunderstood how the joint linking works: you are right when you assign the injected field in each your entities, but you must have between parenthesis an attribute's name from the source entity, not the destination one. In this case, you'd have: `material(referencia)`;
  - For `OrdemProduto`, you have `is_a_Evento` link that uses the "<<uses>>" annotation, JHipster doesn't support that and I can't guarantee it will work.

These two are the most serious problems I see right now, but I'm going to work on #148 so that you'll know when the scheduler fails (when the circular dependency is detected).

**Comment by MathieuAA** [comment]
Okay! with the latest commit (3ce1aaf) I can tell you that these

```
Unidade,Fornecedor,Produto,OrdemProduto,Cliente,
PessoaFisica,PessoaJuridica,Funcionario,VinculoEmpregaticio,
Evento,TipoEvento,EventoFuncionario,EstadoFuncionario,
SalarioBase,FuncaoFuncionario,FechamentoFolhaMensal,
DiarioMensal,PagamentoEfetivoFuncionario,Grade,OrdemProdutoGrade,
ProdutoGrade,Moeda,HistoricoMoeda,TipoProduto,JornadaTrabalho,
RegimeFerias,FeriasGozada,Material,Pessoa,Empresa,DiarioProducao,
DiarioFuncionario,DiarioProducaoSetor,ProdutoMaterial,MotivoFalta,
HorarioDiario,HorarioTermo,Setor
```

are the processed entities and the process fails when only 3 elements remain.

```
Source entity: Telefone, destination entity: undefined, cardinality: one-to-one,
Source entity: ComposicaoBaseCalculo, destination entity: undefined, cardinality: one-to-one,
Source entity: BaseCalculo, destination entity: ComposicaoBaseCalculo, cardinality: many-to-many
```

When you see `undefined`, that means that you tried to link an entity to an enum, which is not possible since enums are just types.

**Comment by lfdubiela** [comment]
you saved hours of rework! thanks for that!
