### ISSUE TITLE
Would be nice to do the reverse (i.e. generate the .xmi from .jhipster files?)

### ISSUE THREAD

**Issue by sdoxsee** [jhipster/jhipster-uml#15]

**Comment by MathieuAA** [comment]
The only use case I can think of is to be able to visualize the generated entites in _any_ UML editor.
That won't work because every editor supports its own version of XMI (that's why each generator has its own parser right now).

However, if we somehow manage to import the JSONs in a UML editor (without using the XMI format), then we could make it work.
We're working on a UML editor (using Sirius, still in alpha stage), and the use case would be something nice to support.

**Comment by sdoxsee** [comment]
That makes sense. Thanks. Using jhipster JSON files as an import format
itself seems too jhipster-specific to be worthwhile IMO. I had ignorantly
assumed xmi files were a common format that could be imported into any uml
editor. Feel free to close this issue as being out of scope.

**Comment by cbornet** [comment]
@sdoxsee Have you tried reversing your java domain source code with your UML editor ? It worked quite well for me with Modelio :-).
