### ISSUE TITLE
Add microserviceName mention

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-uml#168]
@PierreBesson Is there a default value for this? like `className.uncapitalize()`? I assume the user will be able to choose a value for that, right?

**Comment by jdubois** [comment]
The microserviceName is in fact the "baseName" of the application -> it's important to have the same name, because that's what is used by the gateway to map the microservice.

For example, microservice "yolo" is mapped on "/yolo", so we need to store that name as "microserviceName".

This must then be used by JHipster UML to add the "microserviceName" property to the entity:

- JHipster UML will run on the microservice as usual, but needs to add this "microserviceName" (this isn't the case actually)
- Then, when we can generate the same entity on the gateway. JHipster will know this is an entity coming from a microservice as we give it the path to the microservice, and as it just checks this "microserviceName" property
- The entity sub-generator will then only generate the front-end on the gateway, and will add the "/yolo" prefix to the REST requests

**Comment by MathieuAA** [comment]
So... I don't need to add it right? =) If the user is in a JHipster microservice app, I just need to read the  `yo-rc.json` file and be done with it.

However, if the user isn't in a JHipster app, I still have to ask the question.
I assume the same goes for the searchEngine then as it is in the `yo-rc.json` file?

**Comment by jdubois** [comment]
No, when you are generating an entity in a gateway, there is a specific first question: if you want to generate that entity from an existing microservice.
In that case, the gateway will fetch that entity in the microservice's .jhipster folder, and run it locally with the --skip-server option. But it will need to have the microservice name, so it knows on which URL to point the REST request.
So the "microserviceName" is mandatory in an entity generated in a microservice app.

**Comment by MathieuAA** [comment]
Ok, thanks! I'll add it when I can.

**Comment by davidweianibone** [comment]
Hi Mathieu, was this issue implemented already ?
I have generated my microservice entities with the jhipster uml and all my generated json files are missing the microservice name.

**Comment by MathieuAA** [comment]
It has been done. I'll test if everything's ok later.
