### ISSUE TITLE
A better way to generate entities

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-uml#174]
From #171.
What if we generate entities in two steps:
  - First the entities without the relationships;
  - Then add the relationships later.

Performance and maintanability must be evaluated.

**Comment by lsgpimentel** [comment]
I agree that letting the user fail is not user-friendly. That's a drawback. But we, as programmers, already have to think in that kind of thing when we create tables and FK's in a database. That was my point.

> If the user has 3 entities, yo jhipster:entity MyEntity[1..3] would be called 6 times, and that's ok.. but if the user has 30 entities (a very common case, but it's always way more than that) it's not acceptable;
Huh? If the user has 3 entities, you will call `yo jhipster:entity [Entity]` for each entity, like you're already doing today in https://github.com/jhipster/jhipster-uml/blob/master/lib/entity_generator.js#L23
The entity generation step is the only step where you'll need to know the correct order of the entities to generate, since JHipster will create one changelog for each entity. In that case, we can't let entity 2, that references entity 1, be created before it. In the JSON generation step, the order just doesn't matter.

> We don't generate entities, we let JHipster do it because JHipster has some internal mechanisms to detect faulty JSON files and we don't host any template in this project for the sake of atomicity and no-redundancy. So we'd actually have to rely on JHipster the double amount of times for one task.
Yeah, I know. But I'm not suggesting anything different from this. What I proposed changes only the JSON generation step. The ordering will still be necessary in a different step, like I said before, but it should be much simpler.

**Comment by MathieuAA** [comment]
I have three solutions to the problem right now.

I'll update this thread when each test has been concluded to share my results. Or you can tweak the code yourself if you want =) I'd help navigate through if you'd want any help with that.

**Comment by MathieuAA** [comment]
By the way, I've milestoned this task to the "future". Which is whenever it's ready and tested. That doesn't mean I'll only start working on it sometime in the future. It means I'll start working on it anytime, but release it after some other (more important) tasks have been done and released.
However, if it's ready and tested I'll just ship it ASAP -- if we find the best (or the closest to perfect) solution for the problem.

I hope my rythm is okay for you? I like to solve a problem and think about the next problem at the very same time.

**Comment by lsgpimentel** [comment]
Ohh, don't worry about that. If I were in a hurry I would send a pull request myself.

I'll wait until you finish what needs to be done. At your rythm, of course.

Thank you very much for the attention!

**Comment by lsgpimentel** [comment]
Related pull request in generator-jhipster: https://github.com/jhipster/generator-jhipster/pull/3250

I think that this should make the work easier.

**Comment by MathieuAA** [comment]
Oh yes. I'll wait a bit before testing things then =)

**Comment by MathieuAA** [comment]
The only thing I've got to do is disable the scheduler and remove it... only if JHipster's version is > v3.

**Comment by MathieuAA** [comment]
Closing this as all the work has been done in the generator. We only need to disable the scheduler for v1.7.0.
