### ISSUE TITLE
Support StarUML?

### ISSUE THREAD

**Issue by fjarcticfox** [jhipster/jhipster-uml#181]
Will jhipster-uml Support StarUML?

**Comment by MathieuAA** [comment]
Hello, we've seen what this editor was capable of and we decided to drop it mainly because of bugs.
From what I see, their editor is not free (and not open source), but it is available for download (which is kinda weird if you ask me).
I'd have to see if the situation has been improved first, but yeah. That could be possible in the future.
I'll see if the pros outweigh the cons and if it can be done for v1.7.0.

**Comment by MathieuAA** [comment]
Hello again, I've just finished testing it and I must admit I'm impressed by what I've seen.
I'll try to make it available for v1.7.0.

Thanks for taking the time to ask!

**Comment by fjarcticfox** [comment]
Glad to hear that.
Thanks for accept my suggestion.

**Comment by MathieuAA** [comment]
Work is being reported [here](https://github.com/jhipster/jhipster-uml/projects/3).

**Comment by MathieuAA** [comment]
I'm deprecating this project in favor of the JDL, and this is not happening any time soon.
