### ISSUE TITLE
Circular dependency when adding two relationships between two entities

### ISSUE THREAD

**Issue by Paul-Etienne** [jhipster/jhipster-uml#192]
### The issue

Using the JDL language, I am trying to create two entities and link them with two relationships of type OneToOne and OneToMany.
In my example, there are two entities : Country and City. I want the Country to have a list of cities and I want it to hold a reference to a single city as well, the city being the capital of this country.

I am doing this on a fresh install of jHipster.

---
#### The stacktrace

Here's the error I am getting when executing the command "jhipster-uml" :

```
An error has occurred:
	CircularDependencyException
Error message:
	There is a circular dependency in the model.
The processed entities so far: [ No entity could have been handled. ]
The elements that still needed processing: [ Source entity: Country, destination entity: City, cardinality: one-to-one,Source entity: Country, destination entity: City, cardinality: one-to-many ].
Stack trace:
Error
    at Object.<anonymous> (/usr/local/lib/node_modules/jhipster-uml/lib/exceptions/circular_dependency_exception.js:7:41)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/jhipster-uml/lib/scheduler.js:6:35)
    at Module._compile (module.js:541:32)
```

---

### Steps to reproduce

Simply create a jhipster app from scratch, create a model.jh with the code below, execute the command jhipster-uml model.jh and look at the error.

---

### The XMI or JDL file

Here's the JDL code :

```
entity Country {
	name String
}
entity City {
	name String
}

relationship OneToOne {
	Country{capital} to City
}
relationship OneToMany {
	Country{city} to City{country}
}
```

---

### Versions

The version I am using is v1.6.5.

**Comment by MathieuAA** [comment]
Hi, in v1.6.5 (and before), it's normal you have this error... The role of each entity is clear (Country -> City in both relationships), and for these kinds of relationships you can't have them because it would introduce a circular dependency.
That was for v1.6.5. In v1.7.0, there won't be any circular dependency error because the generation order won't matter.

**Comment by Paul-Etienne** [comment]
Oh ok, well if you say it's normal.
I'm not sure I understood correctly why this wouldn't work though.
Could you detail a bit more why these two relationships create a circular dependency ?
Also, before the v1.7.0 is released, how should one do to get these relationships working ? Create one relationship first and then the other one ?

**Comment by MathieuAA** [comment]
Sorry if I was somehow vague, I couldn't answer... The real problem is that the two types of relationships require different order of generation. The One-to-One requires the destination entity to be generated first, the One-to-Many requires the source to be generated first (it's a composition, not an aggregation from the source viewpoint).
As I said, this kind of issue will not be encountered from v1.7.0 onward, as the entity would be generated before the association.

**Comment by Paul-Etienne** [comment]
Alright, thanks for the explanation. I'm looking forward to the next version then.
