### ISSUE TITLE
Add option to export DTOs

### ISSUE THREAD

**Issue by myspivey** [jhipster/jhipster-uml#22]
Per http://jhipster.github.io/using_dtos.html, DTO's, especially for complex cases can be generated, these would be nice to have created during this process.

**Comment by MathieuAA** [comment]
Hi, you can already export DTOs with JHipster-UML. Simply use the `-dto` arg.

**Comment by myspivey** [comment]
Sorry I should have clarified, is there a way during the process to only export the DTO per Table? Not having to create DTOs for each but only a subset is far preferred for readability and cleanliness of code. Also, if possible, can the flags offered me listed somewhere? Currently the documentation does not mention the -dto argument.

**Comment by MathieuAA** [comment]
A PR has been proposed in order to update the wiki. We forgot to add it.
And no, currently there's no way to select which entity is to be DTOed.
If we choose to do it, the best way I can think of right now is to pass the `-dto` flag, then after the parsing, we could just ask the user (with Inquirer) the entities to be DTOed so that we set the flags correctly in the JSONs.
