### ISSUE TITLE
A way to choose to use 'extends AbstractAuditingEntity'

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/jhipster-uml#27]

**Comment by MathieuAA** [comment]
As mentioned in #26, if JHipster doesn't provide a way to do this with the Q&A, we won't (can't) implement this.
Note that this is more of a technical constraint than a "boolean" one. We won't do this because we directly use JHipster to generate the entities (we just call `yo jhipster:entity ...` to do some magic).
Reimplementing the whole process of the entity sub-generator may be painful, and isn't why JHipster-UML was created.

**Comment by VIIgit** [comment]
https://www.npmjs.com/package/generator-jhipster-entity-audit worked for me 👍
