### ISSUE TITLE
If the domain didn't change, the other files seems to be identical, why to create a new liquidbase xml file?

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/jhipster-uml#28]
I am using jhipster-uml in an Agile development, so I constantly go back to my model and change something, but not everything. Most of the time I'm creating new tables and relationships. So, why once we run jhipster-uml not have an option to choose among entities to update? A way like jhipster:entity entity.

**Comment by MathieuAA** [comment]
This may be a good idea... We have to take a closer look at it. I don't want the user choosing (because he/she would have to choose after passing an argument to the command line, and I hate to add anything to the command line) and it should, for me, be transparent to the user.
A way to achieve this would be to detect differences between the existing JSON files and the ones we want to create: "If there are differences, then we create a new JSON. If not, then we don't do anything."

**Comment by CarlKlagba** [comment]
We create a new liquidbase xml file because, for each entity, we change  the property `changelogDate` each time you run the command `jhipster-uml`. That's a mistake from our part, I am making a fix ASAP.

**Comment by CarlKlagba** [comment]
Update to 1.1.3 and tell us if it works smoothly for you.
