### ISSUE TITLE
problem using jhipster-uml

### ISSUE THREAD

**Issue by ouyangshixiong** [jhipster/jhipster-uml#69]
1. jhipster-uml  had to run with command: node jhipster-uml   xxx.uml
The document said:  jhipster-uml   xxx.uml   report No such file or Directory. I'm using docker(jhipster image).

2. all the tables imported without fields and relationships. only empty table imported. I'am using UMLDesigner5.0.0

3. I don't know how to compile jhipster-uml from git source. can you show me an example.

Thank you.

**Comment by MathieuAA** [comment]
Hi,

First of all, I suggest you read the [doc](https://jhipster.github.io/jhipster_uml.html#install).
If you're having problems with a UML class diagram, you have to pass it here. Nobody can help you otherwise.
Finally, you don't need to compile the project. Unless you're a JS compiler, I'm assuming you want to use the last version (from git) of JHipster-UML, and that information is available in the doc.

Next time, I suggest you take the time to read it and then, if you have questions, post your questions here.
