### ISSUE TITLE
Jhipster UML vs Reverse engineering: table name and column name

### ISSUE THREAD

**Issue by AVE-cesar** [jhipster/jhipster-uml#81]
I would like to find a way to use Jhipster and Jhipster UML to do reverse engineering on existing database model. I am quite near a complete solution but I need some improvements on your great tools. I would like to know if you share my point of view.

I have written a tools that can generate a jhipster uml compatible entity file for an existing database but I am lacking the possibility to make a distinction between the name of my entities and the corresponding table name and for column names also.

This is an example of a possible solution:

entity Report(correspondingTableNameInDatabase){
  name(correspondingColumnNameInDatabase) String required maxlength(256)
}

agree or not ?

thanks

**Comment by MathieuAA** [comment]
Hi, I'll be frank: it's not in JHipster-UML's scope to do this (or JHipster's).

That being said, you have quite an interesting idea but there are some limitations:
  - I'm not going to change the JDL's grammar just for this because the answer you're lookiing for is in JHipster's code;
  - Your approach on the matter may not be correct.

You're looking for a way to specify (or find) the table's name as well as any column's name in the database.
JHipster chooses to name the table like this (see the rest of the file to find out how it's done for the columns [here](https://github.com/jhipster/generator-jhipster/blob/master/entity/templates/src/main/java/package/domain/_Entity.java):

    @Table(name = "<%= entityTableName %>")

If I have to change my grammar to specify how a table is named then that the other users would find it as an enhancement that wouldn't do anything, and would likely write the `correspondingTableNameInDatabase` every time an entity is specified. The same goes for columns.
You seem to seek a way to "configure" while there's already a convention in JHipster.

Moreover, even if I do implement it that wouldn't make a difference in behavior as I would still not use the addition to the grammar to specify anything new (JHipster expects one name for an entity, and one name of each of the columns/fields).

If I were to have a choice on the matter, I would not change anything in the JDL (obviously), not change anything in JHipster, but look for a way to find how JHipster names its entities and columns, and how it differs from what is written in the JDL.
If you're lazy to find the solution, look [here](https://github.com/jhipster/generator-jhipster/blob/master/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity.xml), and try to create dummy app, with dummy entities and compare what you find your database and what you have as input in the entity generator.

**Comment by AVE-cesar** [comment]
thanks for your answer

**Comment by jdubois** [comment]
@AVE-cesar you are not the only one who want to do database table reverse-engineering with JHipster -> maybe you could reach out @nromanetti @jeanlouisboudart who are also working on this

**Comment by cbornet** [comment]
@AVE-cesar Why don't you just use the table name as entity name ?

Also, for information, I was able to do something not far by:
* using Netbeans to reverse the DB into a java model
* using Modelio to reverse the java model into an UML diagram

It's not fully automated and we had to modify some things manually. For instance Netbeans didn't detect the many-to-many relationships (don't know if this can be configured in Netbeans), and it mapped sql dates to java.util.Date so we had to change it to the ZonedDateTime type.
But as this must be done only once this is not a big issue and can be done in less than a day.

Note: if the app you want to migrate has a swagger spec, you can also use swagger-codegen to generate the spring controllers and DTOs and then use mapstruct to map the DTOs to the entities.
--> Dropwizard project ported to jhipster in no time !

I think I will write a tip in jhipster with the steps I used when I have time.
